### ISSUE TITLE
Crash running on Dedicated Server but not client. Version 1.10

### ISSUE THREAD

**Issue by phillipinman** [SanAndreasP/TurretModRebirth#1]
Hello, love the mod, but i have a strange issue with a error on the server side, the mod loads fine if it's on a client but otherwise crashes. I've attached the log file.

[error_log.txt](https://github.com/SanAndreasP/TurretModRebirth/files/334760/error_log.txt)

**Comment by SanAndreaP** [comment]
~~Please provide the fml-server-latest.log.~~
Nevermind, I see the problem now! I will fix it immediately.

**Comment by SanAndreaP** [comment]
You can grab the new version fixing this bug here:
http://minecraft.curseforge.com/projects/turret-mod-rebirth/files/2311009
