### ISSUE TITLE
There are no ammunition shown in ammunition tab. Just Enought items doesnt show its recipe.

### ISSUE THREAD

**Issue by DageLV** [SanAndreasP/TurretModRebirth#10]
Do you use Java 8?
Yes

What version of Minecraft do you use?
1.12.1

What version of MinecraftForge do you use?
forge-1.12.1-14.22.0.2474

What version of SanLib do you use?
SanLib-1.12-1.2.0

What version of Turret Mod Rebirth do you use?
TurretMod-1.12-4.0.0-beta.2
 
What is the issue / bug you have encountered? Give us a short description.
Ammunition isnt craftable. Ammo tab is empty on that turret crafting table. Just Enought Items doesnt show the recipe

How can it be reproduced?
Place down the turret crafting table and go to ammunition section. Or press Recipe on JEI.

Please post your log file on https://gist.github.com and provide the link:
Latest https://www.mediafire.com/file/yzy3yzpj5lb9428/latest.log
Latest FML https://www.mediafire.com/file/liwiaw5pexuzpei/fml-client-latest.log

**Comment by SanAndreaP** [comment]
```
12:59:07] [main/ERROR] [sapturretmod/sapturretmod]: Parsing error loading electrolyte generator recipe from /assets/sapturretmod/recipes_sapturretmod/assembly/group_upg.json
com.google.gson.JsonSyntaxException: Json cannot be null
	at de.sanandrew.mods.sanlib.lib.util.JsonUtils.getIntVal(JsonUtils.java:83) ~[JsonUtils.class:?]
	at de.sanandrew.mods.turretmod.registry.assembly.TurretAssemblyRecipes.registerJsonRecipes(TurretAssemblyRecipes.java:102) ~[TurretAssemblyRecipes.class:?]
```
hmmm... I'll look into it.

**Comment by DageLV** [comment]
Just Enought items mod shows recipes for turrets, assembly tables etc, but not the ammunition. Ammunition can be obtained only from creative and thats it. And why i cant input stuff from top using hoppers into generator?

**Comment by SanAndreaP** [comment]
It seems to load the turrets first, then errors trying to load the ammo by invalidly loading a group as a recipe.
Also the generator only accepts items from the sides of the bottom part.

**Comment by SanAndreaP** [comment]
Okay, could you try out this release?
https://github.com/SanAndreasP/TurretModRebirth/releases/download/4.0.0-beta.2.1/TurretMod-1.12-4.0.0-beta.2.1.jar

Given I don't run into this issue myself, you'd have to test it. Please let me know if this fixes it, so I can release it to the public.

**Comment by DageLV** [comment]
Yes. This fixed it. I dont have much time so i didnt checked if they do have crafting recipe, but they do appear in ammunition tab, so i think it will work. Thanks.

**Comment by SanAndreaP** [comment]
nice
