### ISSUE TITLE
Items not being created (Really?)

### ISSUE THREAD

**Issue by Oxykronnos** [SanAndreasP/TurretModRebirth#11]
[ Please replace text in [] with the answer from the above question! ]

Do you use Java 8?
Yes

What version of Minecraft do you use?
1.12.1

What version of MinecraftForge do you use?
8.0.99.99

What version of SanLib do you use?
1.0.2

What version of Turret Mod Rebirth do you use?
4.0.0-beta.2.1
 
What is the issue / bug you have encountered? Give us a short description.
Directly, when you put energy and items in the Turret Assembly table, it doesn't does anything.

How can it be reproduced?
How? How not, much more said. Im using this in a modpack called All the mods 3.

Please post your log file (either in /logs/fml-client-latest.log or /logs/latest.log) on https://gist.github.com and provide the link:
My log is almost empty. There's no lines talking about the Turret mod (just a few discard lines talking about non-existing recipes of other mods).
![hereyouhave](https://user-images.githubusercontent.com/7040689/31300436-fbca4026-aaf3-11e7-9729-c7cf44c244e3.png)

**Comment by SanAndreaP** [comment]
did you give it enough items? (for example you need to give it 5 iron ingots)
When you press shift while hovering over the recipe, it tells you how much you need of each item.

I need to include this info in the next version.

**Comment by Oxykronnos** [comment]
Huh, didn't tried this, i'll try it and say something to you when i do it.

**Comment by Tlecuauhtli** [comment]
This happened to me too, but i put the enough items. 
![2017-10-07_19 31 47](https://user-images.githubusercontent.com/32604428/31312883-4099640a-ab96-11e7-9a60-c75307ff26f6.png)

**Comment by Oxykronnos** [comment]
Do you have the last version?

**Comment by Tlecuauhtli** [comment]
Yes, and this happen just in this turret.

**Comment by SanAndreaP** [comment]
I'll look into it

**Comment by Oxykronnos** [comment]
Maybe is the NBT of the bow only accepting certain damage values?

**Comment by SanAndreaP** [comment]
I fixed it in beta 2.4, it was the fault of the wood planks, as they were defined in the recipe to have a damage value of 32765 (wildcard value) and the assembly table falsely checking if there's an item with this exact value (instead of accepting any damage value)
