### ISSUE TITLE
Items disappear from the assembly table when exit world

### ISSUE THREAD

**Issue by Tlecuauhtli** [SanAndreasP/TurretModRebirth#12]
Do you use Java 8?
Yes

What version of Minecraft do you use?
1.12.2

What version of MinecraftForge do you use?
14.23.0.2486

What version of SanLib do you use?
1.2.0

What version of Turret Mod Rebirth do you use?
4.0.0-beta.2.1
 
What is the issue / bug you have encountered? Give us a short description.
When i put some items in the assembly table and exit the world they disappear

How can it be reproduced?
![lost items](https://user-images.githubusercontent.com/32604428/31319337-fb58c3b8-ac26-11e7-86ec-745a5dbf2162.gif)

Please post your log file (either in /logs/fml-client-latest.log or /logs/latest.log) on https://gist.github.com and provide the link:

It doesn't crash but here it is anyways:
[fml-client-latest.log](https://github.com/SanAndreasP/TurretModRebirth/files/1367076/fml-client-latest.log)

**Comment by SanAndreaP** [comment]
I fixed it in beta 2.4
