### ISSUE TITLE
Config addition request

### ISSUE THREAD

**Issue by ghost** [SanAndreasP/TurretModRebirth#13]
Hi, I would like to start by thanking you for your work and nice addition to the community.
Just wanna ask if it's possible to add a config option for bullets damage, I'm not a Java developer but as I'm looking through the code I see it's fairly easy to request the config option in bullets getDamage() method?

Thank you!

EDIT: as of now it's kinda pointless to protect your base against modded mobs + mods that increase difficulty as they have a lot more HP/Damage in comparision with vanilla mobs.

**Comment by SanAndreaP** [comment]
A config like that is planned.

**Comment by SanAndreaP** [comment]
The config has been rewritten, the new config stuff will be available in the upcoming release
