### ISSUE TITLE
Menu Text Graphic Issue

### ISSUE THREAD

**Issue by InTheBetween** [SanAndreasP/TurretModRebirth#14]
[ Please replace text in [] with the answer from the above question! ]

Do you use Java 8?
[Yes]

What version of Minecraft do you use?
[1.12.2]

What version of MinecraftForge do you use?
[1.12.2-forge1.12.2-14.23.1.2555]

What version of SanLib do you use?
[1.12.1]

What version of Turret Mod Rebirth do you use?
[1.12.2]
 
What is the issue / bug you have encountered? Give us a short description.
[Text graphics not appearing in item menus. Ex. nothing in white/blacklist for turret control, nothing in any categories in the turret tablet.  Graphical glitches when the area is clicked]

How can it be reproduced?
[Open any menu (turret, tablet, etc.)]

![2017-12-06_19 06 34](https://user-images.githubusercontent.com/34324405/33693464-ad65fcaa-dab8-11e7-88be-2c6da75d5fc4.png)
![2017-12-06_19 06 39](https://user-images.githubusercontent.com/34324405/33693465-ad7d1142-dab8-11e7-9cf0-afd8a1531ba2.png)
![2017-12-06_19 06 42](https://user-images.githubusercontent.com/34324405/33693466-ad8fe272-dab8-11e7-8ae2-98ac8bce6dd6.png)]

Please post your log file (either in /logs/fml-client-latest.log or /logs/latest.log) on https://gist.github.com and provide the link:
https://gist.github.com/InTheBetween/7fcc04d7da7ee4effce400807b7a9f59

**Comment by SanAndreaP** [comment]
Can you try disabling shaders in the config (under ```/config/sapturretmod.cfg``` set ```useShaders``` to ```false```)?
If that works your graphics driver needs updating / it doesn't support the shaders used.
If it doesn't try to use just TurretMod and SanLib alone. If that works, it's most likely another mod messing up.

**Comment by SanAndreaP** [comment]
Sooo... any updates on it? Did you get it to work or not?

**Comment by SanAndreaP** [comment]
I'm closing this issue now. If you still have problems, please open a new issue.
