### ISSUE TITLE
Can't start the game (sry for my bad english)

### ISSUE THREAD

**Issue by ghost** [SanAndreasP/TurretModRebirth#15]
I've installed the TurretRebirth mod and I've Installed the SanLib mod both for 1.10.2
And it says pls install SanAndreasP's Mod library but i thinked Sanlib and SanML is the same????

**Comment by SanAndreaP** [comment]
so... did you fix it? (I'm asking because you closed this issue)

Also, next time *fill out the form* provided when creating new issues.
And I NEED logs when reporting issues:

>Please post your log file (either in /logs/fml-client-latest.log or /logs/latest.log) on https://gist.github.com and provide the link:

PS: SanAndreasP's Mod library is just the long name for SanLib, so yes, they're the same.

**Comment by ghost** [comment]
Yes i fixed it
