### ISSUE TITLE
Suggestion(s): Player-turret interaction improvements

### ISSUE THREAD

**Issue by Ithronyar** [SanAndreasP/TurretModRebirth#17]
Just some ideas I had. They're all related to one another, so this post contains multiple suggestions. I suspect these ideas will need some refining, but in theory they should make the mod _much_ nicer to use.

1. Access basic turret GUI without turret control unit
It's kind of annoying when you need the turret control unit to do something as simple as turning a turret on/off. It also adds another required tool to the player's inventory; in heavily modded games, these "essential" items can severely clutter the inventory.
Anyway, this suggestion is simple: If the turret is right-clicked, its GUI can be viewed; no control unit required. The hovering status window when mousing over a turret should still only appear when holding the control unit, however.

2. Turret control unit can be used remotely
To make the turret control unit more useful, it can be used as a remote control for multiple turrets, as long as the turrets are in range (16 blocks? Maybe they could also have control range upgrades). Shift-right-click a turret to link it with the control unit. Then you can turn them on/off, see their viewpoints, set targets, etc. However, their inventory can't be modified (only viewed), unless they have...

3. Remote turret inventory upgrade
A new upgrade item. Using ender magic, the turret control unit can remotely interact with a turret's inventory if the turret has this upgrade installed. Basically, players can remotely add items like ammo and upgrades to turret inventories.

**Comment by SanAndreaP** [comment]
1. I can include the first tab for the "right-click with an empty hand" functionality. That way you can show stats, toggle range visibility, deactivate and dismantle the turret w/o needing the TCU. For more "advanced" stuff like taking out upgrades and setting targets you'd still need a TCU.
2. That sounds neat, but I'd restrict it to one link for the TCU, as lorewise the TCU wouldn't be as "powerful" as the laptop (which was in older versions and is going to be re-implemented).
*The laptop was a remote-TCU for multiple turrets with the capabilities of pre-programming up to 8 turrets (setting targets and upgrading them) before you'd place them down.*
3. sure

**Comment by XanderVeninga** [comment]
when will the laptop be added or is it already added?
