### ISSUE TITLE
Very big request

### ISSUE THREAD

**Issue by xxxLEOPARDxxx** [SanAndreasP/TurretModRebirth#19]
Is it possible to add a full configuration of all upgrades and turrets to configs? I have already somehow reworked your mod from the sources for my build, but this is too difficult for me.
I play with a crazy build mods on mobs. The most powerful turrets live for 30 seconds. In fact, they almost can not kill anyone.
I beg of you, add all the settings of the turrets and upgrades to the config files.

Separately I would like to thank for such a high-quality work! Your mod is incredibly cool and very well made!

**Comment by SanAndreaP** [comment]
See #13
