### ISSUE TITLE
Dismantling doesn't put items in the chest

### ISSUE THREAD

**Issue by kl3cks7r** [SanAndreasP/TurretModRebirth#2]
When I dismantle the turret, it just places the chest and spreads the ammo and upgrade items everywhere. 

Forge: 12.18.0.2000
Bookshelf: 1.10-1.3.0.280
Turret Mod Rebirth: 4.0.0-alpha.5

**Comment by SanAndreaP** [comment]
I'll fix this with a custom container which can hold everything (a chest would be too small given a turret with full ammo and all 36 upgrade slots used)
