### ISSUE TITLE
Packet Data Exceeded

### ISSUE THREAD

**Issue by mxnmnm** [SanAndreasP/TurretModRebirth#20]
Do you use Java 8?
Yes

What version of Minecraft do you use?
1.12.2

What version of MinecraftForge do you use?
14.23.5.2854

What version of SanLib do you use?
1.5.1

What version of Turret Mod Rebirth do you use?
4.0.0-beta.3
 
What is the issue/bug you have encountered? Give us a short description.
Kicked for exceeding packet info limit after clicking whitelist all on the turret filter

How can it be reproduced?
Install lots of mob mods
Click the whitelist all option on the turret

Please post your log file (either in /logs/fml-client-latest.log or /logs/latest.log) on https://gist.github.com and provide the link:
https://gist.github.com/mxnmnm/9a516419baab2431bd372df04d61986f

**Comment by SanAndreaP** [comment]
I've redone the way the UI sends the packets, each entry is gonna be its own packet now to circumvent the limit. The fix will be available in beta 4
