### ISSUE TITLE
Crash with TCU in offhand

### ISSUE THREAD

**Issue by mxnmnm** [SanAndreasP/TurretModRebirth#21]
Do you use Java 8?
Yes

What version of Minecraft do you use?
1.12.2

What version of MinecraftForge do you use?
14.23.5.2854

What version of SanLib do you use?
1.5.1

What version of Turret Mod Rebirth do you use?
4.0.0-beta.3

What is the issue/bug you have encountered? Give us a short description.
Crash when right clicking a turret with a TCU in your offhand

How can it be reproduced?
Hold TCU in offhand
Right click turret

Please post your log file (either in /logs/fml-client-latest.log or /logs/latest.log) on https://gist.github.com and provide the link:
https://gist.github.com/mxnmnm/39607b912a0ad66052418989d458a7a5

**Comment by SanAndreaP** [comment]
already fixed in dev, fixed in the upcoming version
