### ISSUE TITLE
Scaling health blights not taking damage

### ISSUE THREAD

**Issue by mxnmnm** [SanAndreasP/TurretModRebirth#24]
What version of Minecraft do you use?
1.12.2

What version of Minecraft Forge do you use?
14.23.5.2854

What version of SanLib do you use?
1.6.0

What version of Turret Mod Rebirth do you use?
beta 4
 
What is the issue / bug you have encountered? Give us a short description.
The fuel purifier upgrade and ender gain medium don't work against blights from scaling health

How can it be reproduced?
Use flamethrower/laser turret with fuel purifier or ender gain medium upgrade and have them try to shoot a blight

**Comment by SanAndreaP** [comment]
fixed in 8b7c317
