### ISSUE TITLE
Crashes with new version

### ISSUE THREAD

**Issue by mxnmnm** [SanAndreasP/TurretModRebirth#28]
Do you use Java 8?
Yes

What version of Minecraft do you use?
1.12.2

What version of MinecraftForge do you use?
14.23.5.2854

What version of SanLib do you use?
1.6.2

What version of Turret Mod Rebirth do you use?
Beta 4.3

What is the issue/bug you have encountered? Give us a short description.
Crash when entering world previously made wolrd and crash when making a new one

How can it be reproduced?
No clue

Please post your log file (either in /logs/fml-client-latest.log or /logs/latest.log) on https://gist.github.com and provide the link:
crash with previously made world: https://gist.github.com/mxnmnm/1fa3ab7565775b597f94369351497bfd
crash with new world:https://gist.github.com/mxnmnm/2574bda32b4965cc1797d05fe7bdf834

**Comment by SanAndreaP** [comment]
Can you try the new Beta 4.4 and see if it works? If not, i'll just remove the ItemRemapper entirely.

**Comment by mxnmnm** [comment]
So far it seems ok although seeing how the crash happened randomly I can't be 100% sure that it is fixed

**Comment by SanAndreaP** [comment]
Alright, I'll close this issue for now, then. If you encounter another crash, just reply and I'll reopen this again.

**Comment by mxnmnm** [comment]
Yay more issues
https://gist.github.com/mxnmnm/edade188d25d3ad0a18e0dd024438448
https://gist.github.com/mxnmnm/e43e69b8108a14e5450c24213e159e02
https://gist.github.com/mxnmnm/d34bc0fd91be409ef0368bfbaa72c117

**Comment by SanAndreaP** [comment]
I have opened a new issue for you, as this is a different kind of crash than the previous one.
