### ISSUE TITLE
Error in ClientTickHandler

### ISSUE THREAD

**Issue by SanAndreaP** [SanAndreasP/TurretModRebirth#29]
Yay more issues
https://gist.github.com/mxnmnm/edade188d25d3ad0a18e0dd024438448
https://gist.github.com/mxnmnm/e43e69b8108a14e5450c24213e159e02
https://gist.github.com/mxnmnm/d34bc0fd91be409ef0368bfbaa72c117

_Originally posted by @mxnmnm in https://github.com/SanAndreasP/TurretModRebirth/issues/28#issuecomment-799016767_

**Comment by SanAndreaP** [comment]
@mxnmnm Can you please check if the new release fixes this issue?
https://www.curseforge.com/minecraft/mc-mods/turret-mod-rebirth/files/3249841

**Comment by mxnmnm** [comment]
https://gist.github.com/mxnmnm/eea26265934fe5c7c5f8df60afad08b4
https://gist.github.com/mxnmnm/c23097c6b8b795dea4e5b3ae5a4415f9

**Comment by SanAndreaP** [comment]
@mxnmnm Can you check if this is the one that'll fix the issue? https://www.curseforge.com/minecraft/mc-mods/turret-mod-rebirth/files/3269326

**Comment by SanAndreaP** [comment]
I assume this is fixed now? If not, please open a new issue, I'll close this one.
