### ISSUE TITLE
Dismantling gives bad item

### ISSUE THREAD

**Issue by kl3cks7r** [SanAndreasP/TurretModRebirth#3]
After I dismantle the turret, it takes the chest item into one with the value of zero.

![2016-07-08_09 26 17](https://cloud.githubusercontent.com/assets/13091481/16690656/9029388e-44ee-11e6-93a8-d2829ea509e7.png)

Forge: 12.18.0.2000
Bookshelf: 1.10-1.3.0.280
Turret Mod Rebirth: 4.0.0-alpha.5

**Comment by SanAndreaP** [comment]
This will be fixed in the upcoming beta.1 version
