### ISSUE TITLE
Turret lexicon doesn't show any recipes or upgrades.

### ISSUE THREAD

**Issue by Goblin1101** [SanAndreasP/TurretModRebirth#31]
[ Please replace text in [] with the answer from the above question! ]

Do you use Java 8?
[Yes]

What version of Minecraft do you use?
[1.12.2]

What version of MinecraftForge do you use?
[14.23.5.2860]

What version of SanLib do you use?
[1.12.2 - 1.6.0 (1.6.2)]

What version of Turret Mod Rebirth do you use?
[4.0.0 - beta.4.6]
 
What is the issue / bug you have encountered? Give us a short description.
[When I open turret lexicon it doesn't show any recipes, ammo and upgrade information. This is how forcefield turret second page looks like.
![изображение_2022-04-15_185951823](https://user-images.githubusercontent.com/59949976/163568278-bbcd7c2c-068f-4a20-82ba-74af44d26552.png)
]
[latest.log](https://github.com/SanAndreasP/TurretModRebirth/files/8495773/latest.log)

How can it be reproduced?
[I just open any turret page]

Please post your log file (either in /logs/fml-client-latest.log or /logs/latest.log) on https://gist.github.com and provide the link:
[latest.log](https://github.com/SanAndreasP/TurretModRebirth/files/8495773/latest.log)]

**Comment by captinalex1** [comment]
I could be wrong, but I believe the book isn't fully completed yet, as I get the same thing. However JEI and just looking inside the assembly table will show you the recipe, energy consumption and process time of the turrets and their components.  
<img width="1920" alt="Screenshot_5" src="https://user-images.githubusercontent.com/5091550/163692948-c356a716-008b-46d7-8a98-736ec067c9f5.png">
<img width="1920" alt="Screenshot_6" src="https://user-images.githubusercontent.com/5091550/163692949-6076b701-a06e-4fec-a996-58ebf4752c2e.png">

**Comment by SanAndreaP** [comment]
Just cleaning up :)
The 1.12.2 version is not maintained anymore and the current iteration for 1.16 (unreleased, as of writing this) has this problem fixed.
