### ISSUE TITLE
Health upgrade increases max health but not current health

### ISSUE THREAD

**Issue by kl3cks7r** [SanAndreasP/TurretModRebirth#4]
The health upgrade increases the maximum amount of health but not the current health. This makes it so you have to use a repair kit every time you upgrade your turret. Is this intentional?

Forge 12.18.0.2000
Bookshelf 1.10-1.3.0.280
Turret Mod Rebirth 4.0.0-alpha.5

**Comment by SanAndreaP** [comment]
This is intended. I wrote that info down in the turret info tablet.
