### ISSUE TITLE
Not having 'Bookshelf' Coremod crashes game instead of alerting player

### ISSUE THREAD

**Issue by arranreedman** [SanAndreasP/TurretModRebirth#7]
When the required coremod is not installed, the game fatally crashes instead of alerting the user that a prerequisite is not installed as is the standard. You may like to look into it, to avoid mistaken players fooling around trying to solve issues that just require the coremod...

I have included the crash report to help you if needed.
[crash-2016-08-13_15.53.48-client.txt](https://github.com/SanAndreasP/TurretModRebirth/files/416625/crash-2016-08-13_15.53.48-client.txt)

**Comment by SanAndreaP** [comment]
I have now a more "lightweight" dependency (SanLib, which is _not_ a coremod). I also fixed the dependency string of the Turret Mod, so it should give you the "Missing Mods Screen" instead of crashing outright.
The fix will be in in the upcoming version.
