### ISSUE TITLE
[1.10.2] Fatal Error when connecting to LAN world. Network Error.

### ISSUE THREAD

**Issue by RFShahrear** [SanAndreasP/TurretModRebirth#8]
Entering a LAN world causes immediate fatal error. No error in singleplayer world.
Here's the latest log. Error is at Line 45675.
[fml-client-latest.txt](https://github.com/SanAndreasP/TurretModRebirth/files/1074251/fml-client-latest.txt)

**Comment by SanAndreaP** [comment]
```
[16:55:51] [Netty Client IO #1/ERROR] [FML/]: FMLIndexedMessageCodec exception caught
io.netty.handler.codec.DecoderException: java.lang.NullPointerException: Undefined message for discriminator 82 in channel rftoolsdim
```

Can you try without RFTools Dimensions?

**Comment by RFShahrear** [comment]
Turned out neither of the two causes the crash. I'll close the issue.
